<div class="navbar">
  <a href="index.php">Home</a>
  <a href="apply.php" alt="104777308@student.swin.edu.au">Apply</a>
  <a href="jobs.php" alt="10477308@student.swin.edu.au">Jobs</a>
  <a href="enhancements.php" alt="105505856@student.swin.edu.au">Enhance</a>
  <a href="about.php" alt="105551558@student.swin.edu.au">About Us</a>
  <a href="manage.php">Manage</a>
  <a class="icon" href="#"
    ><img src="styles/images/twitter_icon.png" alt="X" width="20"
  /></a>
  <a class="icon" href="https://youtu.be/Vh_ofpbQxjg"
    ><img src="styles/images/youtube_icon.png" alt="YouTube" width="80"
  /></a>
</div>
